[package]
name = "getty"
version = "0.1.0"
edition = "2018"

[features]
default = ["std"]
std = []

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
apple-errnos = "0.1.1"
libc = "0.2.147"

[target.'cfg(target_os = "linux")'.dependencies]
linux-syscalls = "0.1.2"
linux-stat = "0.3.0"
itoap = { version = "1.0.1", features = ["simd"] }
atoi = "2.0.0"
memchr = "2.5.0"
